version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_DATABASE: compositedb
      DB_USER: dlcs
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: dlcs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compositedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
