name: Build & Push Docker Image
description: Builds and pushes Docker images to the DLCS GitHub Packages repositories.

inputs:
  image-name:
    description: 'Identifier for output image in gchr.io/dlcs/*'
    required: true
  dockerfile:
    description: 'Dockerfile to use'
    required: true
  github-token:
    description: 'The GitHub token used when interacting with GCHR'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/dlcs/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,enable=true,prefix=,format=long
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
