name: Build and push Thumbs image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Identifier for output image in gchr.io/dlcs/*'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile to use'
        required: true
        type: string
  workflow_dispatch:

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        if: github.event_name != 'workflow_dispatch'
        id: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/dlcs/${{ inputs.image_name }}
          tags: |
            type=ref,event=branch
            type=sha,enable=true,prefix=,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
